---

name: CD-production

on:  # yamllint disable-line rule:truthy

  release:

    types:
      - published

env:
  PACKAGE_NAME: update-pre-commit
  PYTHON_VERSION: '3.14.x'

permissions:
  contents: read

jobs:

  publish-PyPI:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - shell: bash
      run: |
        # install dependencies and build
        make test-install
        make build

    # https://github.com/marketplace/actions/pypi-publish
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
      with:
        attestations: false
        packages-dir: dist/
        password: ${{ secrets.SECRET_PYPI }}
        print-hash: true
        repository-url: https://upload.pypi.org/legacy/
        verbose: true
        verify-metadata: true

  validate-PyPI:

    needs: [publish-PyPI]

    runs-on: ubuntu-latest

    steps:

    - name: Validate after short wait to ensure publish is complete
      shell: bash
      run: sleep 15

    - name: Checkout source code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - shell: bash
      env:
        INDEX_URL: "https://pypi.org/simple/"
      run: |
        # install package from PyPI and run app to show version
        python -m pip install ${{ env.PACKAGE_NAME }}==${{ github.ref_name }}
        ${{ env.PACKAGE_NAME }} --version

  notify-slack:
    if: always()

    needs: [publish-PyPI, validate-PyPI]

    runs-on: ubuntu-latest

    outputs:
      WORKFLOW_RESULT: ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}

    steps:

    - name: Get Overall Jobs Results
      id: get-overall-jobs-results
      shell: bash
      run: |
        # get overall result from all of the previous jobs
        if "${{ needs.publish-PyPI.result == 'success' && needs.validate-PyPI.result == 'success' }}"; then
          echo "WORKFLOW_RESULT=:white_check_mark:" >> "$GITHUB_OUTPUT"
        else
          echo "WORKFLOW_RESULT=:no_entry:" >> "$GITHUB_OUTPUT"
        fi

    - name: Post message to Slack
      uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CICD }}"
          text: "
              *Repository: ${{ github.repository }}*\n
              *Workflow : ${{ github.workflow }} ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}*\n
              *Tag Name : ${{ github.ref_name }}*
              ```
              URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
              Job: publish-PyPI  - ${{ needs.publish-PyPI.result }}\n
              Job: validate-PyPI - ${{ needs.validate-PyPI.result }}
              ```"
