name: cron-coverage

on:
  schedule:
    - cron: '15 22 * * 0'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.x'

permissions:
  contents: read

jobs:
  coverage-test:

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    outputs:
      COV_PER: ${{ steps.get-coverage-results.outputs.COV_PER }}
      COV_RUN: ${{ steps.get-coverage-results.outputs.COV_RUN }}

    steps:
    - id: checkout-source-code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

    - id: setup-Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - id: install-python-deps
      run: make test-install

    - id: coverage-run
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYTHONUNBUFFERED: "1"
      run: make test

    - id: get-coverage-results
      run: |
        # get coverage results
        ls -l htmlcov/
        echo "COV_RUN=${{ steps.run-coverage-tests.outcome }}"            >> "$GITHUB_OUTPUT"
        echo "COV_PER=$(coverage report | grep TOTAL | awk '{print $6}')" >> "$GITHUB_OUTPUT"

    - id: upload-coverage
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: coverage
        path: htmlcov/
        if-no-files-found: error
        retention-days: 1
        overwrite: true
        compression-level: 6

    - id: checkout-source-code-in-badge-branch
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      with:
        ref: badge

    - id: setup-file-coverage-json
      # create/update coverage.json from template.json
      # { "schemaVersion": 1, "label": "TPL_LABEL", "labelColor": "TPL_LCOLOR", "message": "TPL_MESSAGE", "color": "TPL_COLOR" }
      env:
        LABEL: "Code Coverage"
        LCOLOR: "2e2e2e" # hex color: Dark Charcoal
        MESSAGE: "${{ steps.get-coverage-results.outputs.COV_PER }}"
        COLOR: "2986CC"  # hex color: Muted and Cold Shade of blue
      run: |
        # setup file - coverage.json
        # use template.json to create/replace coverage.json
        sed -e 's/TPL_LABEL/${{ env.LABEL }}/g;s/TPL_LCOLOR/${{ env.LCOLOR }}/g;s/TPL_MESSAGE/${{ env.MESSAGE }}/g;s/TPL_COLOR/${{ env.COLOR }}/g' template.json > coverage.json

    - id: push-commits-to-badge-branch
      shell: bash
      run: |
        if [ ! -z "$(git status --porcelain)" ]; then
          # if the working directory is not clean, push commits to badge
          git config --global user.email "mona-lisa@github.com"
          git config --global user.name "Mona Lisa"
          git add coverage.json
          git commit -m 'create/update coverage.json'
          git push -u origin badge
        fi

  notify-slack:
    if: always()
    needs: [coverage-test]

    runs-on: ubuntu-latest

    steps:

    - name: Post message to Slack
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "*Repository : ${{ github.repository }}*\n*Workflow   : ${{ github.workflow }}*
            ```
            Cron Job Result    : ${{ needs.coverage-test.result }}\n
            Coverage Run       : ${{ needs.coverage-test.outputs.COV_RUN }}\n
            Coverage Percentage: ${{ needs.coverage-test.outputs.COV_PER }}\n
            Workflow URL       : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ```"
