---
name: cron-tasks

on:
  schedule:
    - cron: "30 3 * * 0"

  workflow_dispatch:

env:
  PYTHON_VERSION: "3.14.x"
  UV_VERSION: "0.12.3"

permissions:
  actions: read
  contents: read
  issues: read
  pull-requests: read

jobs:
  pre-badge-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      COV_PER: ${{ steps.get-coverage-results.outputs.COV_PER }}
      COV_RUN: ${{ steps.get-coverage-results.outputs.COV_RUN }}

    steps:
      - name: Checkout source code # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python # https://github.com/marketplace/actions/setup-python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup UV # https://github.com/marketplace/actions/astral-sh-setup-uv
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: "true"

      - name: Install test dependency-group
        shell: bash
        run: make test-only

      - name: Run coverage
        id: run-coverage
        shell: bash
        run: make test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONUNBUFFERED: "1"

      - name: Get coverage results
        id: get-coverage-results
        shell: bash
        run: |
          echo "COV_RUN=${{ steps.run-coverage.outcome }}"                         >> "$GITHUB_OUTPUT"
          echo "COV_PER=$(uv run coverage report | grep TOTAL | awk '{print $6}')" >> "$GITHUB_OUTPUT"

      - name: Upload coverage # https://github.com/marketplace/actions/upload-artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: htmlcov/
          if-no-files-found: error
          retention-days: 1
          overwrite: true
          compression-level: 6

  badge-coverage:
    runs-on: ubuntu-latest
    needs: pre-badge-coverage

    permissions:
      contents: write

    steps:
      - name: Run setup-badge-action # https://github.com/tagdots/setup-badge-action
        id: badge-coverage
        uses: tagdots/setup-badge-action@294661aa1f149b59dfe1cd187539eca7f8f0fabf # 1.0.18
        with:
          badge-name: coverage
          badge-url: https://github.com/${{ github.repository }}/actions/workflows/cron-tasks.yaml
          label: "Code Coverage"
          message: "${{ needs.pre-badge-coverage.outputs.COV_PER }}"

  stale-workflow-runs:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Run delete-workflow-runs # https://github.com/tagdots/delete-workflow-runs
        id: delete-workflow-runs
        uses: tagdots/delete-workflow-runs@4303b7da352de2004b0c5f118420cf9f1d63a370 # 1.2.33
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-url: ${{ github.server_url }}/${{ github.repository }}
          max-days: 10
          dry-run: false

      - name: Get data and set GITHUB_OUTPUT
        id: get_data
        shell: bash
        run: |
          cat data_dict.log | jq .

  stale-issues-prs:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Run stale # https://github.com/actions/stale
        id: stale-issues-prs
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
        with:
          stale-issue-message: "This issue is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 3 days after stale"
          days-before-stale: 5
          days-before-close: 3
          delete-branch: true

  stale-branches:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Run delete-branches # https://github.com/tagdots/delete-branches
        id: delete-branches
        uses: tagdots/delete-branches@7ab458c4f92b1dcd058cce7ebd57bb88ec6d21ab # 1.2.16
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-url: ${{ github.server_url }}/${{ github.repository }}
          max-idle-days: 10
          exclude-branches: "badges"
          dry-run: false

  update-pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Run update-pre-commit # https://github.com/tagdots/update-pre-commit-action
        id: update-pre-commit
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: tagdots/update-pre-commit-action@a80688d12cf761973e340674bcf552af366afba5 # 1.0.28
        with:
          file: .pre-commit-config.yaml
          dry-run: false
          open-pr: true

  notify-slack:
    if: always()
    needs:
      [
        badge-coverage,
        stale-workflow-runs,
        stale-issues-prs,
        stale-branches,
        update-pre-commit,
      ]
    runs-on: ubuntu-latest

    outputs:
      WORKFLOW_RESULT: ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}

    steps:
      - name: Get overall jobs results
        id: get-overall-jobs-results
        shell: bash
        run: |
          if ${{
            needs.badge-coverage.result == 'success'
            && needs.stale-workflow-runs.result == 'success'
            && needs.stale-issues-prs.result == 'success'
            && needs.stale-branches.result == 'success'
            && needs.update-pre-commit.result == 'success' }}; then
            echo "WORKFLOW_RESULT=:white_check_mark:" >> "$GITHUB_OUTPUT"
          else
            echo "WORKFLOW_RESULT=:no_entry:" >> "$GITHUB_OUTPUT"
          fi

      - name: Post message to Slack # https://github.com/slackapi/slack-github-action
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
          payload: |
            channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
            text: "
              *Repository: ${{ github.repository }}*\n
              *Workflow : ${{ github.workflow }} ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}*
              ```
              URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
              Job: badge-coverage      - ${{ needs.badge-coverage.result }}\n
              Job: stale-workflow-runs - ${{ needs.stale-workflow-runs.result }}\n
              Job: stale-issues-prs    - ${{ needs.stale-issues-prs.result }}\n
              Job: stale-branches      - ${{ needs.stale-branches.result }}\n
              Job: update-pre-commit   - ${{ needs.update-pre-commit.result }}
              ```"
